name: Tanush.me - Deploy to AWS Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.SERVER_IP }} <<'ENDSSH'
        cd /home/ubuntu/portfolio-tanush
        git pull
        sudo rm -rf /var/www/html/portfolio-tanush
        ls /var/www/html
        sudo cp -r /home/ubuntu/portfolio-tanush/ /var/www/html/portfolio-tanush
        ls /var/www/html
        sudo systemctl restart nginx
        sudo systemctl status nginx
        ENDSSH
